// <auto-generated />
using FindE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220624122259_PrimeiraVersao")]
    partial class PrimeiraVersao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("FindE.Features.Conta.Models.ContaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Perfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Perfil = 0,
                            Senha = "af023865c44e4fcf1fd229c1788f74f07e7fc518ea2b8c33c0f9d903bea6b3ff",
                            Usuario = "sistema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
